### ISSUE TITLE
Commit hash not importing

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#104]
@sorcerykid

Error: `ValueError: SHA b'cb2f00a0ac76ece238145bc91913bd8d4d9bfd16' could not be resolved, git returned: b'cb2f00a0ac76ece238145bc91913bd8d4d9bfd16 missing'`

Repo: https://bitbucket.org/sorcerykid/auth_rx
Hash: [cb2f00a0ac76ece238145bc91913bd8d4d9bfd16](https://bitbucket.org/sorcerykid/auth_rx/commits/cb2f00a0ac76ece238145bc91913bd8d4d9bfd16)

```
Traceback (most recent call last):
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/snip/contentdb/app/tasks/__init__.py", line 50, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/snip/contentdb/app/tasks/importtasks.py", line 370, in makeVCSRelease
    gitDir, repo = cloneRepo(release.package.repo, ref=branch, recursive=True)
  File "/home/snip/contentdb/app/tasks/importtasks.py", line 297, in cloneRepo
    repo.create_head("myhead", ref).checkout()
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/git/repo/base.py", line 366, in create_head
    return Head.create(self, path, commit, force, logmsg)
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/git/refs/symbolic.py", line 546, in create
    return cls._create(repo, path, cls._resolve_ref_on_create, reference, force, logmsg)
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/git/refs/symbolic.py", line 497, in _create
    target = repo.rev_parse(str(reference))
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/git/repo/fun.py", line 334, in rev_parse
    obj = name_to_object(repo, rev)
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/git/repo/fun.py", line 150, in name_to_object
    return Object.new_from_sha(repo, hex_to_bin(hexsha))
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/git/objects/base.py", line 64, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/git/db.py", line 37, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(sha))
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/git/cmd.py", line 1077, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/git/cmd.py", line 1066, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/home/snip/contentdb/env/lib/python3.5/site-packages/git/cmd.py", line 1030, in _parse_object_header
    raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
ValueError: SHA b'cb2f00a0ac76ece238145bc91913bd8d4d9bfd16' could not be resolved, git returned: b'cb2f00a0ac76ece238145bc91913bd8d4d9bfd16 missing'
```

**Comment by rubenwardy** [comment]
Should be fixed now
