### ISSUE TITLE
Release of game with submodules fails with permission error

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest/contentdb#245]
## Summary
Upon creating a release of the `mesecons_lab` game i'm getting greeted by an error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/cdb/app/tasks/__init__.py", line 51, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/cdb/app/tasks/importtasks.py", line 305, in makeVCSRelease
    archiver.create(destPath)
  File "/usr/local/lib/python3.6/site-packages/git_archive_all.py", line 223, in create
    archive = ZipFile(path.abspath(output_path), 'w')
  File "/usr/local/lib/python3.6/zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '/var/cdb/uploads/zUri9ZexQ4.zip'
```

##### Steps to reproduce

* Create a new package with the `mesecons_lab` game (https://github.com/BuckarooBanzay/mesecons_lab)
* Create a release with the tag `1.1`

##### Notes

I tried to debug that error myself but i'm pretty new to the whole codebase so i'm just posting this here, maybe i'll get around to it again :smile: 

**Also**: thanks for this awesome piece of software :+1:

**Comment by BuckarooBanzay** [comment]
Update:

After i ran `chmod 777 data/uploads` a new error appears:

```
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
worker_1    |     R = retval = fun(*args, **kwargs)
worker_1    |   File "/home/cdb/app/tasks/__init__.py", line 51, in __call__
worker_1    |     return TaskBase.__call__(self, *args, **kwargs)
worker_1    |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
worker_1    |     return self.run(*args, **kwargs)
worker_1    |   File "/home/cdb/app/tasks/importtasks.py", line 305, in makeVCSRelease
worker_1    |     archiver.create(destPath)
worker_1    |   File "/usr/local/lib/python3.6/site-packages/git_archive_all.py", line 260, in create
worker_1    |     self.archive_all_files(archiver)
worker_1    |   File "/usr/local/lib/python3.6/site-packages/git_archive_all.py", line 307, in archive_all_files
worker_1    |     archiver(path.join(self.main_repo_abspath, file_path), path.join(self.prefix, file_path))
worker_1    |   File "/usr/local/lib/python3.6/site-packages/git_archive_all.py", line 253, in archiver
worker_1    |     add_file(file_path, arcname)
worker_1    |   File "/usr/local/lib/python3.6/site-packages/git_archive_all.py", line 227, in add_file
worker_1    |     archive.write(file_path, arcname, ZIP_DEFLATED)
worker_1    |   File "/usr/local/lib/python3.6/zipfile.py", line 1617, in write
worker_1    |     zinfo = ZipInfo.from_file(filename, arcname)
worker_1    |   File "/usr/local/lib/python3.6/zipfile.py", line 507, in from_file
worker_1    |     st = os.stat(filename)
worker_1    | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/XwDA0w9GdF/mods/display_modpack/display_api/display_api/API.md'
```

Looks like it is having some issues with the git submodules :thinking: is that even supported?

**Comment by rubenwardy** [comment]
Git submodules are certainly supported, either that library has randomly broken or there's something in particular with the repository used

**Comment by BuckarooBanzay** [comment]
> Git submodules are certainly supported, either that library has randomly broken or there's something in particular with the repository used

It is a wip project of mine and consists of 5 submodules (https://github.com/BuckarooBanzay/mesecons_lab/blob/master/.gitmodules) other than that i don't think it is "special" :shrug:

**Comment by rubenwardy** [comment]
This is an [upstream issue](https://github.com/Kentzo/git-archive-all/issues/85), so there's not much I can do about it without forking the library or reimplementing it myself

**Comment by rubenwardy** [comment]
I have a feeling this is due to this incorrect .gitmodules config in display_api: https://github.com/pyrollo/display_modpack/blob/6135b3a60c4adb270b1a3a05b8d3449ecfa68148/.gitmodules

**Comment by BuckarooBanzay** [comment]
closing this, the error was due to a misconfig on a repository (`.gitmodules`)
thanks @rubenwardy :+1:
