### ISSUE TITLE
Unable to update translations

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#435]
Running ./utils/update_trans.sh just results in empty files

**Comment by rubenwardy** [comment]
```
$ ./utils/update_trans.sh 
extracting messages from app/__init__.py
extracting messages from app/default_data.py
extracting messages from app/maillogger.py
extracting messages from app/markdown.py
extracting messages from app/querybuilder.py
extracting messages from app/rediscache.py
extracting messages from app/sass.py
extracting messages from app/template_filters.py
extracting messages from app/blueprints/__init__.py
extracting messages from app/blueprints/admin/__init__.py
extracting messages from app/blueprints/admin/actions.py
extracting messages from app/blueprints/admin/admin.py
extracting messages from app/blueprints/admin/audit.py
extracting messages from app/blueprints/admin/email.py
extracting messages from app/blueprints/admin/licenseseditor.py
extracting messages from app/blueprints/admin/tagseditor.py
extracting messages from app/blueprints/admin/versioneditor.py
extracting messages from app/blueprints/admin/warningseditor.py
extracting messages from app/blueprints/api/__init__.py
extracting messages from app/blueprints/api/auth.py
extracting messages from app/blueprints/api/endpoints.py
extracting messages from app/blueprints/api/support.py
extracting messages from app/blueprints/api/tokens.py
extracting messages from app/blueprints/donate/__init__.py
extracting messages from app/blueprints/github/__init__.py
extracting messages from app/blueprints/gitlab/__init__.py
extracting messages from app/blueprints/homepage/__init__.py
extracting messages from app/blueprints/metrics/__init__.py
extracting messages from app/blueprints/modnames/__init__.py
extracting messages from app/blueprints/notifications/__init__.py
extracting messages from app/blueprints/packages/__init__.py
extracting messages from app/blueprints/packages/game_hub.py
extracting messages from app/blueprints/packages/packages.py
extracting messages from app/blueprints/packages/releases.py
extracting messages from app/blueprints/packages/reviews.py
extracting messages from app/blueprints/packages/screenshots.py
extracting messages from app/blueprints/report/__init__.py
extracting messages from app/blueprints/tasks/__init__.py
extracting messages from app/blueprints/threads/__init__.py
extracting messages from app/blueprints/thumbnails/__init__.py
extracting messages from app/blueprints/todo/__init__.py
extracting messages from app/blueprints/users/__init__.py
extracting messages from app/blueprints/users/account.py
extracting messages from app/blueprints/users/claim.py
extracting messages from app/blueprints/users/profile.py
extracting messages from app/blueprints/users/settings.py
extracting messages from app/blueprints/zipgrep/__init__.py
extracting messages from app/logic/LogicError.py
extracting messages from app/logic/__init__.py
extracting messages from app/logic/game_support.py
extracting messages from app/logic/graphs.py
extracting messages from app/logic/package_validator.py
extracting messages from app/logic/packages.py
extracting messages from app/logic/releases.py
extracting messages from app/logic/screenshots.py
extracting messages from app/logic/uploads.py
extracting messages from app/models/__init__.py
extracting messages from app/models/packages.py
extracting messages from app/models/threads.py
extracting messages from app/models/users.py
extracting messages from app/tasks/__init__.py
extracting messages from app/tasks/emails.py
extracting messages from app/tasks/forumtasks.py
extracting messages from app/tasks/importtasks.py
extracting messages from app/tasks/pkgtasks.py
extracting messages from app/tasks/usertasks.py
extracting messages from app/tasks/webhooktasks.py
extracting messages from app/tasks/zipgrep.py
extracting messages from app/tasks/minetestcheck/__init__.py
extracting messages from app/tasks/minetestcheck/config.py
extracting messages from app/tasks/minetestcheck/tree.py
extracting messages from app/templates/404.html (extensions="jinja2.ext.autoescape,jinja2.ext.with_")
Traceback (most recent call last):
  File "/home/ruben/dev/web/contentdb/env/bin/pybabel", line 8, in <module>
    sys.exit(main())
  File "/home/ruben/dev/web/contentdb/env/lib/python3.10/site-packages/babel/messages/frontend.py", line 1034, in main
    return CommandLineInterface().run(sys.argv)
  File "/home/ruben/dev/web/contentdb/env/lib/python3.10/site-packages/babel/messages/frontend.py", line 960, in run
    return cmdinst.run()
  File "/home/ruben/dev/web/contentdb/env/lib/python3.10/site-packages/babel/messages/frontend.py", line 528, in run
    for filename, lineno, message, comments, context in extracted:
  File "/home/ruben/dev/web/contentdb/env/lib/python3.10/site-packages/babel/messages/extract.py", line 208, in extract_from_dir
    yield from check_and_call_extract_file(
  File "/home/ruben/dev/web/contentdb/env/lib/python3.10/site-packages/babel/messages/extract.py", line 272, in check_and_call_extract_file
    for message_tuple in extract_from_file(
  File "/home/ruben/dev/web/contentdb/env/lib/python3.10/site-packages/babel/messages/extract.py", line 314, in extract_from_file
    return list(extract(method, fileobj, keywords, comment_tags,
  File "/home/ruben/dev/web/contentdb/env/lib/python3.10/site-packages/babel/messages/extract.py", line 402, in extract
    for lineno, funcname, messages, comments in results:
  File "/home/ruben/dev/web/contentdb/env/lib/python3.10/site-packages/jinja2/ext.py", line 808, in babel_extract
    extensions[import_string(extension_name)] = None
  File "/home/ruben/dev/web/contentdb/env/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
updating catalog translations/nl/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/eo/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/zh_Hant/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/uk/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/lzh/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/sv/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/ru/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/de/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/pl/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/tr/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/cs/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/ms/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/fa/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/fr/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/zh_Hans/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/pt_BR/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/gl/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/ja/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/vi/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/hu/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/da/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/sk/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/it/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/es/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/el/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/lv/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/id/LC_MESSAGES/messages.po based on translations/messages.pot
updating catalog translations/nb_NO/LC_MESSAGES/messages.po based on translations/messages.pot
```
