### ISSUE TITLE
GitHub webhook fails to read message

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#465]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/cdb/app/blueprints/github/__init__.py", line 136, in webhook
    title = json["head_commit"]["message"].partition("\n")[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by rubenwardy** [comment]
a7364990bd4dd2940c84b5c581bd809935372093
